apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            # Standard Kubernetes CPU-based autoscaling.
            autoscaling.knative.dev/class:  hpa.autoscaling.knative.dev
            autoscaling.knative.dev/metric: cpu
#            autoscaling.knative.dev/target: "10"
        spec:
          container:
            image: docker.io/kingdo/knative-helloworld-python
            env:
              - name: TARGET
                value: "Python Sample v1"